---
- name: Managing user passwords
  hosts: all

  tasks:
    - name: Change user password
      become: true
      ansible.builtin.user:
        name: george
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"
