---
- name: Enable service on firewalld
  hosts: localhost
  tasks:

  - name: Open port for http
    ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    notify:
    - Reload firewalld
  
  - name: Ensure firewalld is running
    ansible.builtin.service:
      name: firewalld
      state: started

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
