---
- name: Install packages thru loop
  hosts: localhost
  vars:
    packages:
      - ftp
      - telnet
      - htop

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
