---
- name: Installing and Running apache
  hosts: localhost

  tasks:
    - name: Install apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start apache
      ansible.builtin.service:
        name: httpd
        state: started
