---
- name: Download Tomcat from tomcat.apache.org
  hosts: all

  tasks:
    - name: Create a directory for tomcat
      become: true
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        mode: "0755"
        owner: root
        group: root
    - name: Download tomcat using get_url
      become: true
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75-deployer.tar.gz
        dest: /opt/tomcat
        mode: "0755"
        group: ec2-user
        owner: ec2-user
