---
- name: Create users thru loop
  hosts: localhost
  vars:
    users: ['jerry', 'kramer', 'eliane']

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item }}"
      with_items: "{{ users }}"
